### ISSUE TITLE
Provide a mechanism that takes backoff values from a hard-coded sequence

### ISSUE THREAD

**Issue by gajus** [myndzi/simple-backoff#1]
```js
var SequenceBackoff = require('simple-backoff').SequenceBackoff;

var backoff = new SequenceBackoff({
  sequence: [
    50,
    100,
    100,
    5000
  ]
});

console.log(backoff.next(), backoff.next(), backoff.next(), backoff.next(), backoff.next(), backoff.next());

// 50, 100, 100, 5000, 5000, 5000

```

Useful when you want to have a burst of retries and then fall-back into long pause.

**Comment by myndzi** [comment]
Published version 1.1.0 to the beta tag -- does this do what you want? I named it FixedBackoff to avoid confusion with the term 'sequence' used elsewhere in the readme. You can install with `npm install simple-backoff@beta` to try it out.

**Comment by gajus** [comment]
Yup. Thank you.

**Comment by myndzi** [comment]
OK, moved to latest
